apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockpitapp
  namespace: cockpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cockpitapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cockpitapp
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        args:
        - |
          sleep 5
          python manage.py makemigrations platforms
          python manage.py migrate platforms
          python manage.py makemigrations user
          python manage.py migrate user
          python manage.py makemigrations k8s
          python manage.py migrate k8s
          python manage.py runserver 0.0.0.0:8000
        image: deekshaaa/cockpitapp-d:1.0
        imagePullPolicy: Always
        env:
          - name: GUACAMOLE_HOST
            value: guacamole-svc.guacamole.svc.cluster.local:8080
          - name: GUACAMOLE_USERNAME
            value: guacadmin
          - name: GUACAMOLE_PASSWORD
            value: guacadmin
          - name: GUACAMOLE_DB_NAME
            value: guacamole-db
          - name: GUACAMOLE_DB_USER
            value: guacamole
          - name: GUACAMOLE_DB_PASSWORD
            value: guacamole
          - name: GUACAMOLE_DB_HOST
            value: guacamole-pg-svc.postgres.svc.cluster.local
          - name: GUACAMOLE_DB_PORT
            value: "5432"
          - name: PLATFORM_DB_NAME
            value: platform-db
          - name: PLATFORM_DB_USER
            value: platform
          - name: PLATFROM_DB_PASSWORD
            value: platform
          - name: PLATFORM_DB_HOST
            value: platform-pg-svc.postgres.svc.cluster.local
          - name: PLATFORM_DB_PORT
            value: "5432"
          - name: MESSAGE_BROKER_URL
            value: amqp://rabbitmq.rabbitmq.svc.cluster.local

          ## Optional Envs
          - name: AWS_ACCESS_KEY_ID
            value: AKIATP5UWSXHUQNAIAMO
          - name: AWS_SECRET_ACCESS_KEY
            value: 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
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_POLL_DELAY_SECONDS
            value: "30"
          - name: AWS_MAX_ATTEMPTS
            value: "3000"
          - name: AWS_TIMEOUT_SECONDS
            value: "3000"
          - name: EMAIL_HOST_USER
            value: cockpit010@gmail.com
          - name: EMAIL_HOST_PASSWORD
            value: b8670eb6d66882063dbe
          - name: JENKINS_CONFIG
            value: "/config"
          - name: JENKINS_TOKEN
            value: 11ab4cf8a214c1c730005e0767a4995b0c
          - name: JENKINS_ADMIN_USER
            value: cockpitadmin
          - name: JENKINS_ADMIN_PASSWORD
            value: 030e7617f1a4
          - name: JENKINS_DOCKER_DEAMON
            value: "tcp://44.205.52.222:2375"
          - name: GRAFANA_API_TOKEN
            value: 'eyJrIjoiT1lOa2FnYzIwVjJETlZraGlZNm1Cd2FnRHUwQTRwajkiLCJuIjoiY29ja3BpdC10ZXN0IiwiaWQiOjF9'
          - name: GRAFANA_HOST
            value: '184.72.69.81:3000'
        name: cockpitapp
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        
